"""removing the repettion of backref

Revision ID: 1746925b8389
Revises: 3e1714d75fcc
Create Date: 2024-10-19 13:08:36.283515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1746925b8389'
down_revision = '3e1714d75fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('buses_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'drivers', ['driver_id'], ['driver_id'])
        batch_op.drop_column('busDriverId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('busDriverId', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('buses_ibfk_1', 'drivers', ['busDriverId'], ['driver_id'])
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
