"""Cradded refrencee of garage manager to garage

Revision ID: 3f68c5bf1274
Revises: f7d9fc06978a
Create Date: 2024-11-11 15:38:22.464187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f68c5bf1274'
down_revision = 'f7d9fc06978a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('managerId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'garManagers', ['managerId'], ['managerId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('managerId')

    # ### end Alembic commands ###
