"""Adding password atrribute in Driver class

Revision ID: 4ed9f423e95b
Revises: e01653484bc1
Create Date: 2024-12-06 13:14:35.732021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed9f423e95b'
down_revision = 'e01653484bc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_password', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('driver_password')

    # ### end Alembic commands ###
