"""added the length of garLocation in the Garage class

Revision ID: 593fc11d8b6f
Revises: 3f68c5bf1274
Create Date: 2024-12-04 05:29:25.606315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '593fc11d8b6f'
down_revision = '3f68c5bf1274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garages', schema=None) as batch_op:
        batch_op.alter_column('garLocation',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garages', schema=None) as batch_op:
        batch_op.alter_column('garLocation',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
