"""Start afresh

Revision ID: e01653484bc1
Revises: 5c04928ad766
Create Date: 2024-12-06 11:58:22.512322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01653484bc1'
down_revision = '5c04928ad766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=50), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('user_profile_pic', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('driver_no', sa.String(length=20), nullable=True),
    sa.Column('driver_name', sa.String(length=50), nullable=False),
    sa.Column('driver_email', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('driver_email')
    )
    op.create_table('garManagers',
    sa.Column('managerId', sa.Integer(), nullable=False),
    sa.Column('managerName', sa.String(length=50), nullable=False),
    sa.Column('managerEmail', sa.String(length=50), nullable=False),
    sa.Column('managerNo', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('managerId')
    )
    op.create_table('buses',
    sa.Column('busId', sa.Integer(), nullable=False),
    sa.Column('busModel', sa.String(length=50), nullable=False),
    sa.Column('busPlateNo', sa.String(length=50), nullable=False),
    sa.Column('busBatteryModel', sa.String(length=50), nullable=False),
    sa.Column('busBatteryComapny', sa.String(length=50), nullable=False),
    sa.Column('busSeatsNo', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('busId'),
    sa.UniqueConstraint('busPlateNo')
    )
    op.create_table('garages',
    sa.Column('garId', sa.Integer(), nullable=False),
    sa.Column('garName', sa.String(length=50), nullable=False),
    sa.Column('garLocation', sa.String(length=250), nullable=False),
    sa.Column('garServices', sa.Text(), nullable=True),
    sa.Column('managerId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['managerId'], ['garManagers.managerId'], ),
    sa.PrimaryKeyConstraint('garId'),
    sa.UniqueConstraint('garLocation'),
    sa.UniqueConstraint('garName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garages')
    op.drop_table('buses')
    op.drop_table('garManagers')
    op.drop_table('drivers')
    op.drop_table('user')
    # ### end Alembic commands ###
