"""applying table declaration to avoid errors in relationships

Revision ID: 68aa58aee811
Revises: 736d8f2fbd0b
Create Date: 2024-10-19 12:41:09.975497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68aa58aee811'
down_revision = '736d8f2fbd0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('driver_no', sa.String(length=20), nullable=True),
    sa.Column('driver_name', sa.String(length=50), nullable=False),
    sa.Column('driver_email', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('driver_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    # ### end Alembic commands ###
