"""added battery company to bus model

Revision ID: e994167716b0
Revises: 72ac8cfc3cdb
Create Date: 2024-10-29 20:54:48.927180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e994167716b0'
down_revision = '72ac8cfc3cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('busBatteryComapny', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_column('busBatteryComapny')

    # ### end Alembic commands ###
